// Mock Campaigns Data
export const mockCampaigns = [
  {
    id: 1,
    name: 'Summer Sale 2025',
    description: 'Q3 promotional campaign',
    status: 'in_progress',
    start_date: '2025-06-01',
    end_date: '2025-08-31',
    total_ads: 10,
    approved_ads: 6,
    denied_ads: 1,
    pending_ads: 3,
    created_at: '2025-05-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'Holiday Campaign',
    description: 'End of year holiday promotions',
    status: 'waiting',
    start_date: '2025-11-01',
    end_date: '2025-12-31',
    total_ads: 5,
    approved_ads: 0,
    denied_ads: 0,
    pending_ads: 5,
    created_at: '2025-10-01T10:00:00Z',
  },
  {
    id: 3,
    name: 'Brand Awareness',
    description: 'Ongoing brand awareness campaign',
    status: 'approved',
    start_date: '2025-09-01',
    end_date: '2025-10-31',
    total_ads: 8,
    approved_ads: 8,
    denied_ads: 0,
    pending_ads: 0,
    created_at: '2025-08-15T10:00:00Z',
  },
  {
    id: 4,
    name: 'Product Recall',
    description: 'Product recall notification campaign',
    status: 'denied',
    start_date: '2025-08-15',
    end_date: '2025-09-30',
    total_ads: 2,
    approved_ads: 0,
    denied_ads: 2,
    pending_ads: 0,
    created_at: '2025-08-01T10:00:00Z',
  },
  {
    id: 5,
    name: 'Spring Launch',
    description: 'New product line launch',
    status: 'waiting',
    start_date: '2026-03-01',
    end_date: '2026-05-31',
    total_ads: 3,
    approved_ads: 0,
    denied_ads: 0,
    pending_ads: 3,
    created_at: '2025-10-10T10:00:00Z',
  },
]

// Mock Ads Data
export const mockAds = [
  {
    id: 1,
    short_id: 'abc123',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Summer Sale Banner - 50% Off',
    description: 'Main promotional banner for summer sale',
    format: 'Banner',
    dimensions: '1200x628',
    status: 'approved',
    created_at: '2025-05-20T09:00:00Z',
  },
  {
    id: 2,
    short_id: 'def456',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Product Carousel - Featured Items',
    description: 'Carousel showcasing top selling products',
    format: 'Carousel',
    dimensions: '1080x1080',
    status: 'waiting',
    created_at: '2025-06-02T09:00:00Z',
  },
  {
    id: 3,
    short_id: 'ghi789',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Video Ad - 15 Second Promo',
    description: 'Short video highlighting summer deals',
    format: 'Video',
    dimensions: '1920x1080',
    status: 'denied',
    created_at: '2025-06-03T09:00:00Z',
  },
  {
    id: 4,
    short_id: 'jkl012',
    campaign_id: 2,
    campaign_name: 'Holiday Campaign',
    name: 'Holiday Special Banner',
    description: 'End of year holiday promotion',
    format: 'Banner',
    dimensions: '1200x628',
    status: 'waiting',
    created_at: '2025-10-01T09:00:00Z',
  },
  {
    id: 5,
    short_id: 'mno345',
    campaign_id: 2,
    campaign_name: 'Holiday Campaign',
    name: 'Gift Guide Carousel',
    description: 'Holiday gift suggestions carousel',
    format: 'Carousel',
    dimensions: '1080x1080',
    status: 'waiting',
    created_at: '2025-10-02T09:00:00Z',
  },
  {
    id: 6,
    short_id: 'pqr678',
    campaign_id: 3,
    campaign_name: 'Brand Awareness',
    name: 'Brand Story Video',
    description: 'Our company mission and values',
    format: 'Video',
    dimensions: '1920x1080',
    status: 'approved',
    created_at: '2025-09-01T09:00:00Z',
  },
  {
    id: 7,
    short_id: 'stu901',
    campaign_id: 3,
    campaign_name: 'Brand Awareness',
    name: 'Customer Testimonial Banner',
    description: 'Happy customer reviews',
    format: 'Banner',
    dimensions: '1200x628',
    status: 'approved',
    created_at: '2025-09-05T09:00:00Z',
  },
  {
    id: 8,
    short_id: 'vwx234',
    campaign_id: 3,
    campaign_name: 'Brand Awareness',
    name: 'Instagram Story - Behind the Scenes',
    description: 'BTS content for Instagram stories',
    format: 'Story',
    dimensions: '1080x1920',
    status: 'approved',
    created_at: '2025-09-10T09:00:00Z',
  },
  {
    id: 9,
    short_id: 'yza567',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Email Header - Summer Sale',
    description: 'Email campaign header graphic',
    format: 'Email',
    dimensions: '600x200',
    status: 'approved',
    created_at: '2025-05-25T09:00:00Z',
  },
  {
    id: 10,
    short_id: 'bcd890',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Social Media Square Post',
    description: 'Square format for social feeds',
    format: 'Social',
    dimensions: '1080x1080',
    status: 'approved',
    created_at: '2025-05-28T09:00:00Z',
  },
  {
    id: 11,
    short_id: 'efg123',
    campaign_id: 2,
    campaign_name: 'Holiday Campaign',
    name: 'Black Friday Teaser',
    description: 'Coming soon teaser for Black Friday',
    format: 'Banner',
    dimensions: '1200x628',
    status: 'waiting',
    created_at: '2025-10-05T09:00:00Z',
  },
  {
    id: 12,
    short_id: 'hij456',
    campaign_id: 3,
    campaign_name: 'Brand Awareness',
    name: 'LinkedIn Company Banner',
    description: 'Updated company page banner',
    format: 'Banner',
    dimensions: '1584x396',
    status: 'approved',
    created_at: '2025-09-15T09:00:00Z',
  },
  {
    id: 13,
    short_id: 'klm789',
    campaign_id: 1,
    campaign_name: 'Summer Sale 2025',
    name: 'Mobile App Banner',
    description: 'In-app promotional banner',
    format: 'Mobile',
    dimensions: '750x1334',
    status: 'in_progress',
    created_at: '2025-06-01T09:00:00Z',
  },
  {
    id: 14,
    short_id: 'nop012',
    campaign_id: 2,
    campaign_name: 'Holiday Campaign',
    name: 'Cyber Monday Flash Sale',
    description: '24-hour flash sale promotion',
    format: 'Banner',
    dimensions: '1200x628',
    status: 'waiting',
    created_at: '2025-10-08T09:00:00Z',
  },
  {
    id: 15,
    short_id: 'qrs345',
    campaign_id: 3,
    campaign_name: 'Brand Awareness',
    name: 'YouTube Pre-Roll Ad',
    description: '6-second bumper ad',
    format: 'Video',
    dimensions: '1920x1080',
    status: 'approved',
    created_at: '2025-09-20T09:00:00Z',
  },
]

// Mock Recent Activity
export const mockRecentActivity = [
  {
    id: 1,
    ad_name: 'Summer Sale Banner',
    campaign_name: 'Summer Sale 2025',
    status: 'waiting',
    date: '2025-10-19',
  },
  {
    id: 2,
    ad_name: 'Product Launch Video',
    campaign_name: 'Holiday Campaign',
    status: 'approved',
    date: '2025-10-18',
  },
  {
    id: 3,
    ad_name: 'Social Media Post',
    campaign_name: 'Brand Awareness',
    status: 'denied',
    date: '2025-10-17',
  },
  {
    id: 4,
    ad_name: 'Email Banner',
    campaign_name: 'Summer Sale 2025',
    status: 'approved',
    date: '2025-10-16',
  },
  {
    id: 5,
    ad_name: 'Display Ad',
    campaign_name: 'Holiday Campaign',
    status: 'waiting',
    date: '2025-10-15',
  },
]

// Mock Dashboard Stats
export const mockDashboardStats = {
  total_campaigns: 12,
  active_campaigns: 8,
  pending_approvals: 23,
  approved_this_month: 45,
}

// Mock Calendar Events
export const mockCalendarEvents = [
  {
    id: 'campaign-1',
    type: 'campaign',
    title: 'Summer Sale 2025',
    start: '2025-06-01',
    end: '2025-08-31',
    status: 'in_progress',
  },
  {
    id: 'campaign-2',
    type: 'campaign',
    title: 'Holiday Campaign',
    start: '2025-11-01',
    end: '2025-12-31',
    status: 'waiting',
  },
  {
    id: 'campaign-3',
    type: 'campaign',
    title: 'Brand Awareness',
    start: '2025-09-01',
    end: '2025-10-31',
    status: 'approved',
  },
]

// Mock User Profile
export const mockUserProfile = {
  id: 1,
  first_name: 'John',
  last_name: 'Smith',
  email: 'john@company.com',
  phone: '(555) 123-4567',
  profile_photo_url: null,
  is_on_vacation: false,
}

// Mock Company/Business Profile
export const mockCompanyProfile = {
  id: 1,
  company_name: "Scott's RV Truck & Auto Repair, Inc.",
  logo_url: null,
  website: 'https://scottsstruckandauto.com',
  facebook_page: 'scottsrvtruck',
  facebook_page_id: '100054318528604',
  instagram_account: '@scottsrvtruck',
  category: 'Auto Repair & Service',
  company_overview: "Whether it's your everyday commuting car, heavy duty truck or your RV, we have the training, latest equipment and experience to be your trusted repair shop. Stop in and see us!",
}

// Mock Approvers
export const mockApprovers = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Smith',
    email: 'john.smith@scottsrvtruck.com',
    phone: '(555) 123-4567',
    is_decision_maker: true,
    status: 'active',
    invited_at: '2025-01-15T10:00:00Z',
    accepted_at: '2025-01-15T11:30:00Z',
  },
  {
    id: 2,
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.johnson@scottsrvtruck.com',
    phone: '(555) 234-5678',
    is_decision_maker: false,
    status: 'active',
    invited_at: '2025-01-20T09:00:00Z',
    accepted_at: '2025-01-20T14:20:00Z',
  },
  {
    id: 3,
    first_name: 'Michael',
    last_name: 'Davis',
    email: 'michael.davis@scottsrvtruck.com',
    phone: '(555) 345-6789',
    is_decision_maker: false,
    status: 'pending',
    invited_at: '2025-02-01T08:00:00Z',
    accepted_at: null,
  },
  {
    id: 4,
    first_name: 'Emily',
    last_name: 'Rodriguez',
    email: 'emily.rodriguez@scottsrvtruck.com',
    phone: '(555) 456-7890',
    is_decision_maker: true,
    status: 'active',
    invited_at: '2025-02-10T10:30:00Z',
    accepted_at: '2025-02-10T15:45:00Z',
  },
]
